language: cpp
compiler: gcc
sudo: required
git:
  depth: 9999999
matrix:
  include:
  - env:
    - TARGET=linux-server
    - RUN_TESTS=true
    os: linux
    dist: trusty
    addons:
      apt:
        update: true
        packages:
        - build-essential
        - gnome-devel
        - cmake
        - git
        - libnetcdf-dev
        - libproj-dev
        - libjasper-dev
        - libcurl3
        - libwxbase3.0-dev
      artifacts:
        s3_region: eu-central-1
        debug: true
        paths:
        - $(ls *.deb | tr "\n" ":")
  - env:
    - TARGET=osx-server
    - RUN_TESTS=true
    os: osx
    osx_image: xcode7.3
    addons:
      artifacts:
        s3_region: eu-central-1
        debug: true
        paths:
        - $(ls *.dmg | tr "\n" ":")
  - env:
    - TARGET=linux-desktop
    - RUN_TESTS=true
    os: linux
    dist: trusty
    addons:
      apt:
        update: true
        packages:
        - build-essential
        - gnome-devel
        - cmake
        - git
        - libnetcdf-dev
        - libproj-dev
        - libjasper-dev
        - libcurl3
        - libwxgtk3.0-dev
      artifacts:
        s3_region: eu-central-1
        debug: true
        paths:
        - $(ls *.deb | tr "\n" ":")
  - env:
    - TARGET=osx-desktop
    - RUN_TESTS=true
    os: osx
    osx_image: xcode7.3
    addons:
      artifacts:
        s3_region: eu-central-1
        debug: true
        paths:
        - $(ls *.dmg | tr "\n" ":")
  - env:
    - TARGET=coverage-scan
    - RUN_TESTS=false
    os: linux
    dist: trusty
    addons:
      apt:
        update: true
        packages:
        - build-essential
        - gnome-devel
        - cmake
        - git
        - libnetcdf-dev
        - libproj-dev
        - libjasper-dev
        - libcurl3
        - libwxgtk3.0-dev
        - lcov
  - env:
    - TARGET=coverity-scan
    - RUN_TESTS=false
    - secure: bXqSgc197UXhkRbLXXj/naGt/giYeM4HnOT4wyXLnL30QqXkmHuzA9jalaghnZYZv6nUiySFr+6ZivWs0ofJHYHEbS4vzE2NG11m+bWwmKbWrmX/gw+PBahg27pZXlVXel1yD4QNG2Gf3SU2yLBFdsZa7tLmfOHnddSUeJ/K8X2DZn7KNGGNfh0lm7JsZf7BhGul4q2J7vVlgqJqXBn+UiuXLrdCn/u3NhtWXpf7zFMI+MjVlXGx7hWj1HqVC43MAVOE3DVzupq93BtxDyTHRrdUZrMHf9rZtKRsr+F3F7xKS9ztJnTM16lDGjoZqeIf7kVj3okCPRIRsUSxx9roKu2ynBvBs8ZMtf37iQWcGJTkMZzV+4sK4aNEcmxPZC4LpigQl9WspZ42wNOvCW2pNsLAB7SAG7ktu3FETlZSMyQyHZHvs2zavc8MvRKHRKUOonhv8QKRTnB1aBDCp1bHpPSzhZ2CURjx8VGY5ZaGF8nJUs+YGEbzt2sDSUpW5vwPxX6lSlASVJI7eI5XMpyMlL8nS7zWP+g6CraeCnE/Hz1liWwm7RE/ONAG3a7KG6Ns6xWida/PtwmhE6qvMStRdY/okVIxD1I6f5w5L/Ek7viXuPxURCIktqc0iGEAqalJoCNi/Xhi0BurkEhvcTP2lWErEMGHsAC470tiGr6ZhGc=
    os: linux
    dist: trusty
    branches:
      only:
      - nightly
    before_install:
    - if [[ "$TRAVIS_BRANCH" != "nightly" ]]; then exit 0; fi
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN
      CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    addons:
      apt:
        update: true
        packages:
        - build-essential
        - gnome-devel
        - cmake
        - git
        - libnetcdf-dev
        - libproj-dev
        - libjasper-dev
        - libcurl3
        - libwxgtk3.0-dev
      coverity_scan:
        project:
          name: atmoswing/atmoswing
          description: Build submitted via Travis CI
        notification_email: pascal.horton@giub.unibe.ch
        build_command_prepend: cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DGDAL_ROOT=$HOME/.libs
        build_command: make -j $(nproc)
        branch_pattern: coverity-scan
cache:
  directories:
  - "$HOME/.libs"
install:
- chmod +x ci/travis/dependencies-${TRAVIS_OS_NAME}.sh
- travis_wait 30 ci/travis/dependencies-${TRAVIS_OS_NAME}.sh
script:
- chmod +x ci/travis/run-${TARGET}.sh
- travis_wait 40 ci/travis/run-${TARGET}.sh
- if [ "$RUN_TESTS" = true ] ; then cd tests && ctest -V ; fi
after_success:
- cd ..
- cpack -C release -G DEB
- ls -lha
- if [[ "$TRAVIS_BRANCH" != "nightly" ]] && [[ "$TRAVIS_BRANCH" != "release" ]]; then
  exit 0; fi
before_deploy:
- git config --local user.name "Pascal Horton"
- git config --local user.email "horton.pascal@gmail.com"
- git tag "$TRAVIS_BRANCH-$(date +'%Y-%m-%d')-$(git log --format=%h -1)"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZJcSZq3z8loWs0djYPfCYGTCaDJ7f9FWFHEeTuVtrRtDyDc9e5RRYje5RhFSdVWiXc6pocgM5/+wynomZGv2TZ6sX2GylyXXc36arEW+TLuxdp0uLZ2lmyiLqO9GUQr6rXqYIe6/EGuMmZ9eS4mzJeYoo8FxlFXe2TE0H3nBtWc4zfWjFs5wzR6uI8efkJuNEaeoxgmEq7+p8E0Ip3zdoYiE9/HYGmu8S87mDpmgHGnvPJzmgScHr709apCf//xHE5QvBNTKfOQrt9H1VDRJN4TF+Ga0a0VthX1W+Be0iQMlMr6M8UzWBzyWUiGOm/O+3LiSLItp3kAWvf+tyKTsK2RqbJzx0XnmRam26IbUoW3ZL9DSbt+C+2qfLnv8lSl8T0Rg/RbA6tzqUpJB+1ffK6xRwWui55JJBn1hEbTpHPOTZxa/XwvXXPyiq92TMeDrEKrQ/CHZ7Vuu65QkRC132fInT3EVJoePWTvPHHbDQbH0cL5iERtwnXM2/GbXjPZGx7BLsQLHBKbpmwuV6spR7+aJZLYVrnePHijp9VBp8UudLlSM3hwAGUE/nFL0X/WHvP+If5AsqM7tpq9b7BjjHGCiSNI6P/SJhDeU+4V/b5uTZv8Tmb+myTcdFcjMfhIuxUdVK566Lskc4rrz9hoOUPdZuVCKdltkp4gHUt4U81I=
  file: "*.deb"
  on:
    repo: atmoswing/atmoswing
    branch: nightly
