language: cpp
compiler: gcc
sudo: required
git:
  depth: 9999999
matrix:
  include:
  - env:
    - TARGET=linux-server
    - RUN_TESTS=true
    - DEPLOY=true
    os: linux
    dist: trusty
    addons:
      apt:
        update: true
        packages:
        - build-essential
        - gnome-devel
        - cmake
        - git
        - libnetcdf-dev
        - libproj-dev
        - libjasper-dev
        - libcurl3
        - libwxbase3.0-dev
  - env:
    - TARGET=osx-server
    - RUN_TESTS=true
    - DEPLOY=true
    os: osx
    osx_image: xcode7.3
  - env:
    - TARGET=linux-desktop
    - RUN_TESTS=true
    - DEPLOY=true
    os: linux
    dist: trusty
    addons:
      apt:
        update: true
        packages:
        - build-essential
        - gnome-devel
        - cmake
        - git
        - libnetcdf-dev
        - libproj-dev
        - libjasper-dev
        - libcurl3
        - libwxgtk3.0-dev
  - env:
    - TARGET=osx-desktop
    - RUN_TESTS=true
    - DEPLOY=true
    os: osx
    osx_image: xcode7.3
  - env:
    - TARGET=coverage-scan
    - RUN_TESTS=false
    - DEPLOY=false
    os: linux
    dist: trusty
    addons:
      apt:
        update: true
        packages:
        - build-essential
        - gnome-devel
        - cmake
        - git
        - libnetcdf-dev
        - libproj-dev
        - libjasper-dev
        - libcurl3
        - libwxgtk3.0-dev
        - lcov
  - env:
    - TARGET=coverity-scan
    - RUN_TESTS=false
    - DEPLOY=false
    - secure: bXqSgc197UXhkRbLXXj/naGt/giYeM4HnOT4wyXLnL30QqXkmHuzA9jalaghnZYZv6nUiySFr+6ZivWs0ofJHYHEbS4vzE2NG11m+bWwmKbWrmX/gw+PBahg27pZXlVXel1yD4QNG2Gf3SU2yLBFdsZa7tLmfOHnddSUeJ/K8X2DZn7KNGGNfh0lm7JsZf7BhGul4q2J7vVlgqJqXBn+UiuXLrdCn/u3NhtWXpf7zFMI+MjVlXGx7hWj1HqVC43MAVOE3DVzupq93BtxDyTHRrdUZrMHf9rZtKRsr+F3F7xKS9ztJnTM16lDGjoZqeIf7kVj3okCPRIRsUSxx9roKu2ynBvBs8ZMtf37iQWcGJTkMZzV+4sK4aNEcmxPZC4LpigQl9WspZ42wNOvCW2pNsLAB7SAG7ktu3FETlZSMyQyHZHvs2zavc8MvRKHRKUOonhv8QKRTnB1aBDCp1bHpPSzhZ2CURjx8VGY5ZaGF8nJUs+YGEbzt2sDSUpW5vwPxX6lSlASVJI7eI5XMpyMlL8nS7zWP+g6CraeCnE/Hz1liWwm7RE/ONAG3a7KG6Ns6xWida/PtwmhE6qvMStRdY/okVIxD1I6f5w5L/Ek7viXuPxURCIktqc0iGEAqalJoCNi/Xhi0BurkEhvcTP2lWErEMGHsAC470tiGr6ZhGc=
    os: linux
    dist: trusty
    branches:
      only:
      - nightly
    before_install:
    - if [[ "$TRAVIS_BRANCH" != "nightly" ]]; then exit 0; fi
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN
      CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    addons:
      apt:
        update: true
        packages:
        - build-essential
        - gnome-devel
        - cmake
        - git
        - libnetcdf-dev
        - libproj-dev
        - libjasper-dev
        - libcurl3
        - libwxgtk3.0-dev
      coverity_scan:
        project:
          name: atmoswing/atmoswing
          description: Build submitted via Travis CI
        notification_email: pascal.horton@giub.unibe.ch
        build_command_prepend: cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DGDAL_ROOT=$HOME/.libs
        build_command: make -j $(nproc)
        branch_pattern: coverity-scan
cache:
  directories:
  - "$HOME/.libs"
install:
- chmod +x ci/travis/dependencies-${TRAVIS_OS_NAME}.sh
- travis_wait 30 ci/travis/dependencies-${TRAVIS_OS_NAME}.sh
script:
- chmod +x ci/travis/run-${TARGET}.sh
- travis_wait 40 ci/travis/run-${TARGET}.sh
- if [ "$RUN_TESTS" = true ] ; then cd tests && ctest -V ; fi
after_success:
- cd ..
- cpack -C release -G DEB
- ls -lha
deploy:
  provider: gcs
  access_key_id: GOOG2DVQVS5OULIG7WIU4B7F
  secret_access_key:
    secure: QVTqXZ54wsQhUu+QcYQATIuwVe27ZIl+3XnccDL7Q2NUalWulj5p4EyQ5+JmKhUYzdRujCH08ASuQiKtb/vW5q0WnNsElFBixLk2rhUTR7AG7v1Tk20fZkAczha5xtC/jfyr1v5DdqzQJYAUnBsV+9Zr2oNLeSj7YbUuJk9GwLdfdc4DKJ4+AKIZR6n9OqtVYVbMZB89W8l2t/20fO/XOuKBLSiG23K9R9dlv6eawF/9nFPx+EcuSBnkOFBa+Cq0xFKRx/N3LHDhFPtpV5s+hH1Oenbcw2l4KwMwwSaVxCerMnyWW0Hu6Mrcn2P7KlCsOBtt1kKxXHDLmwRZdSUVO+DJKt+/jDAjRncqN++rFnb+B7SbHEBiCfUGuW2xfLPr6W5hKxmuHUC+5LnC0uVwPSpvEzMAAU4Xip7M66U1CxwLHH9/CfnNdTXAorYBbDVBEr5PdpVjgtZoih4oeZjrGsIWW98tfrcfOOiLHQnRb2Bc0oOq1lMguRINg1t67kJKuCFKnIQSzYpkVQ7BkXwl0f460cZ24X3lXVCPatNDvT+SI0QL6LJgiF9psPncQGm9olKyBy6jb1MTEl9NTjKoyWLIbi+JIg66ub0hmzDa4IBJtGWm5MCg4O4v5TpL64qcd5HK5U/odMpXgK5DvjBF3NoejKTRTRmy94dYB5/vGpA=
  bucket: atmoswing-deploy
  skip_cleanup: true
  acl: public-read
  on:
    repo: atmoswing/atmoswing
    branch: nightly
    condition: $DEPLOY = true
